-- AlterTable
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'STANDARD';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "subtotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountMotif" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountApprovedById" TEXT;

-- AddForeignKey
DO $$ BEGIN
  ALTER TABLE "Order" ADD CONSTRAINT "Order_discountApprovedById_fkey"
    FOREIGN KEY ("discountApprovedById") REFERENCES "User"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
