export const ROLES = [
  'SUPER_ADMIN',
  'ADMIN',
  'GESTIONNAIRE',
  'CAISSIER',
  'MAGASINIER',
  'CUISINIER',
  'LIVREUR',
  'CLIENT',
] as const;

export type AppRole = (typeof ROLES)[number];

export const PERMISSION_CATALOG: { key: string; label: string }[] = [
  { key: '*', label: 'Accès complet (toutes permissions)' },
  { key: 'admin.ecrire', label: 'Gérer les établissements et la configuration' },
  { key: 'users.voir', label: 'Voir les utilisateurs' },
  { key: 'users.creer', label: 'Créer et modifier les utilisateurs' },
  { key: 'ventes.voir', label: 'Voir les ventes' },
  { key: 'ventes.creer', label: 'Créer une vente' },
  { key: 'ventes.annuler', label: 'Annuler une vente' },
  { key: 'ventes.remise', label: 'Appliquer une remise' },
  { key: 'prix.modifier', label: 'Modifier un prix' },
  { key: 'commandes.voir', label: 'Voir les commandes' },
  { key: 'commandes.creer', label: 'Créer une commande' },
  { key: 'commandes.annuler', label: 'Annuler une commande' },
  { key: 'catalogue.voir', label: 'Voir le catalogue' },
  { key: 'catalogue.modifier', label: 'Créer et modifier un produit' },
  { key: 'stock.voir', label: 'Voir le stock' },
  { key: 'stock.entree', label: 'Effectuer une entrée stock' },
  { key: 'stock.sortie', label: 'Effectuer une sortie stock' },
  { key: 'stock.transfert', label: 'Transférer et valider une réception' },
  { key: 'stock.inventaire', label: 'Effectuer un inventaire' },
  { key: 'stock.inventaire.valider', label: 'Valider un inventaire' },
  { key: 'stock.pertes', label: 'Déclarer une perte' },
  { key: 'stock.pertes.valider', label: 'Valider une perte' },
  { key: 'stock.fefo.deroger', label: 'Déroger au FEFO (autre lot)' },
  { key: 'achats.voir', label: 'Voir les achats et fournisseurs' },
  { key: 'achats.modifier', label: 'Créer un achat' },
  { key: 'achats.recevoir', label: 'Réceptionner un achat' },
  { key: 'cuisine.voir', label: 'Voir l’écran cuisine' },
  { key: 'cuisine.statut', label: 'Changer le statut cuisine' },
  { key: 'livraison.voir', label: 'Voir les livraisons' },
  { key: 'livraison.maj', label: 'Affecter et clôturer une livraison' },
  { key: 'gps.envoyer', label: 'Envoyer la position GPS' },
  { key: 'clients.voir', label: 'Voir les clients' },
  { key: 'clients.modifier', label: 'Créer et modifier un client' },
  { key: 'zones.voir', label: 'Voir les zones de livraison' },
  { key: 'zones.modifier', label: 'Modifier les zones de livraison' },
  { key: 'factures.voir', label: 'Voir les factures' },
  { key: 'rapports.voir', label: 'Consulter les rapports et bénéfices' },
  { key: 'paiements.valider', label: 'Valider un paiement' },
  { key: 'sync.voir', label: 'Voir la synchronisation' },
  { key: 'systeme.voir', label: 'Voir l’état système' },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ['*'],
  ADMIN: ['*'],
  GESTIONNAIRE: [
    'ventes.voir',
    'stock.voir',
    'rapports.voir',
    'commandes.voir',
    'catalogue.voir',
    'catalogue.modifier',
    'sync.voir',
    'systeme.voir',
    'livraison.voir',
    'livraison.maj',
    'factures.voir',
    'users.voir',
    'clients.voir',
    'clients.modifier',
    'zones.voir',
    'zones.modifier',
    'stock.inventaire',
    'stock.inventaire.valider',
    'stock.pertes',
    'stock.pertes.valider',
    'stock.entree',
    'stock.transfert',
    'achats.voir',
    'achats.modifier',
    'achats.recevoir',
    'ventes.remise',
  ],
  CAISSIER: [
    'ventes.voir',
    'ventes.creer',
    'ventes.remise',
    'commandes.voir',
    'catalogue.voir',
    'factures.voir',
    'clients.voir',
    'clients.modifier',
    'zones.voir',
  ],
  MAGASINIER: [
    'stock.voir',
    'stock.entree',
    'stock.sortie',
    'stock.inventaire',
    'stock.inventaire.valider',
    'stock.pertes',
    'stock.pertes.valider',
    'stock.transfert',
    'catalogue.voir',
    'achats.voir',
    'achats.modifier',
    'achats.recevoir',
  ],
  CUISINIER: ['cuisine.voir', 'cuisine.statut', 'commandes.voir'],
  LIVREUR: ['livraison.voir', 'livraison.maj', 'gps.envoyer'],
  CLIENT: ['catalogue.voir', 'commandes.creer', 'zones.voir'],
};
